name: Build AuraROM (Sixteen)

on:
  workflow_dispatch:
    inputs:
      samfw_link:
        description: 'SamFW Direkt İndirme Linkini Buraya Yapıştırın:'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        target: [a24]

    steps:
      - name: Repoyu Çek (Checkout)
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Disk Alanı Boşalt
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Build Ortamını Hazırla
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            7zip attr ccache clang ffmpeg \
            libbrotli-dev libgtest-dev libprotobuf-dev libunwind-dev libpcre2-dev \
            libzstd-dev linux-modules-extra-$(uname -r) lld protobuf-compiler webp
          sudo modprobe erofs f2fs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Anahtarları oluştur (Secrets içinde tanımlı olmalı)
          echo -n "${{ secrets.PLATFORM_KEY_PK8 }}" | base64 --decode > security/unica_platform.pk8
          echo -n "${{ secrets.PLATFORM_KEY_PEM }}" | base64 --decode > security/unica_platform.x509.pem

      - name: JDK 17 Kurulumu
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Bağımlılıkları Derle
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/build_dependencies.sh

      - name: Firmware İndir ve Hazırla
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          mkdir -p out/odin/SM-A245F_TUR
          curl -L -o out/odin/SM-A245F_TUR/firmware.zip '${{ github.event.inputs.samfw_link }}'
          unzip out/odin/SM-A245F_TUR/firmware.zip -d out/odin/SM-A245F_TUR/
          touch out/odin/SM-A245F_TUR/.downloaded
          rm -rf out/odin/SM-A245F_TUR/firmware.zip

      - name: ROM Derleme İşlemi
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/extract_fw.sh
          ./scripts/make_rom.sh

      - name: PixelDrain'e Yükle
        env:
          PIXELDRAIN_API_KEY: ${{ secrets.PIXELDRAIN_API_KEY }}
        run: |
          cd out
          ROM_FILE=$(ls *.zip | head -n 1)
          if [ ! -z "$ROM_FILE" ]; then
            echo "Yükleniyor: $ROM_FILE"
            curl -T "$ROM_FILE" -u ":$PIXELDRAIN_API_KEY" https://pixeldrain.com/api/file/
          else
            echo "HATA: ROM dosyası bulunamadı!"
            exit 1
          fi
